using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MMXOnline
{
    public class BadWords
    {
        public static readonly string[] badWords =
        {
             "2 girls 1 cup",
             "2 girls one cup",
             "2g1c",
             "4r5e",
             "a_s_s",
             "a2m",
             "a55",
             "ahole",
             "anal",
             "anal impaler",
             "anal leakage",
             "analprobe",
             "anilingus",
             "anus",
             "apeshit",
             "ar5e",
             "arian",
             "arrse",
             "arse",
             "arses",
             "arsehole",
             "aryan",
             "ass",
             "ass fuck",
             "ass hole",
             "assbag",
             "assbandit",
             "assbang",
             "assbanged",
             "assbanger",
             "assbangs",
             "assbite",
             "assclown",
             "asscock",
             "asscracker",
             "asses",
             "assface",
             "assfaces",
             "assfuck",
             "assfucker",
             "ass-fucker",
             "assfukka",
             "assgoblin",
             "assh0le",
             "asshat",
             "ass-hat",
             "asshead",
             "assho1e",
             "asshole",
             "assholes",
             "asshopper",
             "ass-jabber",
             "assjacker",
             "asslick",
             "asslicker",
             "assmaster",
             "assmonkey",
             "assmucus",
             "assmunch",
             "assmuncher",
             "assnigger",
             "asspirate",
             "ass-pirate",
             "assshit",
             "assshole",
             "asssucker",
             "asswad",
             "asswhole",
             "asswipe",
             "asswipes",
             "auto erotic",
             "autoerotic",
             "azazel",
             "azz",
             "b!tch",
             "b00bs",
             "b17ch",
             "b1tch",
             "bastard",
             "bastardo",
             "bastards",
             "bi+ch",
             "bitch",
             "bitch tit",
             "bitchass",
             "bitched",
             "bitcher",
             "bitchers",
             "bitches",
             "bitchin",
             "bitching",
             "bitchtits",
             "bitchy",
             "black cock",
             "bull shit",
             "bullshit",
             "bullshits",
             "bullshitted",
             "bullturds",
             "bumblefuck",
             "bunny fucker",
             "butthole",
             "c.0.c.k",
             "c.o.c.k.",
             "c.u.n.t",
             "c0ck",
             "c-0-c-k",
             "chinc",
             "chincs",
             "chink",
             "chinky",
             "circlejerk",
             "clusterfuck",
             "cocaine",
             "coccydynia",
             "cock",
             "c-o-c-k",
             "cock pocket",
             "cock snot",
             "cock sucker",
             "cockass",
             "cockbite",
             "cockblock",
             "cockburger",
             "cockeye",
             "cockface",
             "cockfucker",
             "cockhead",
             "cockholster",
             "cockjockey",
             "cockknocker",
             "cockknoker",
             "cocklump",
             "cockmaster",
             "cockmongler",
             "cockmongruel",
             "cockmonkey",
             "cockmunch",
             "cockmuncher",
             "cocknose",
             "cocknugget",
             "cocks",
             "cockshit",
             "cocksmith",
             "cocksmoke",
             "cocksmoker",
             "cocksniffer",
             "cocksuck",
             "cocksucked",
             "cocksucker",
             "cock-sucker",
             "cocksuckers",
             "cocksucking",
             "cocksucks",
             "cocksuka",
             "cocksukka",
             "cockwaffle",
             "coon",
             "coonnass",
             "coons",
             "cooter",
             "coprolagnia",
             "coprophilia",
             "corksucker",
             "crap",
             "crappy",
             "crikey",
             "cunt",
             "c-u-n-t",
             "cunt hair",
             "cuntass",
             "cuntbag",
             "cuntface",
             "cunthole",
             "cunthunter",
             "cuntlick",
             "cuntlicker",
             "cuntrag",
             "cunts",
             "cuntsicle",
             "cuntslut",
             "cunt-struck",
             "cyberfuc",
             "cyberfuck",
             "cyberfucked",
             "cyberfucker",
             "cyberfucking",
             "dammit",
             "damn",
             "damned",
             "damnit",
             "darkie",
             "dendrophilia",
             "dick",
             "dick head",
             "dick hole",
             "dick shy",
             "dickbag",
             "dickbeaters",
             "dickdipper",
             "dickface",
             "dickflipper",
             "dickfuck",
             "dickfucker",
             "dickhead",
             "dickheads",
             "dickhole",
             "dickish",
             "dick-ish",
             "dickjuice",
             "dickmilk",
             "dickmonger",
             "dickripper",
             "dicks",
             "dicksipper",
             "dickslap",
             "dick-sneeze",
             "dicksucker",
             "dicksucking",
             "dicktickler",
             "dickwad",
             "dickweasel",
             "dickweed",
             "dickwhipper",
             "dickwod",
             "dickzipper",
             "dink",
             "dinks",
             "dipship",
             "dirsa",
             "dumass",
             "dumb ass",
             "dumbass",
             "dumbasses",
             "dumbcunt",
             "dumbfuck",
             "dumbshit",
             "ejaculate",
             "ejaculated",
             "ejaculates",
             "ejaculating",
             "ejaculatings",
             "ejaculation",
             "f u c k",
             "f u c k e r",
             "f.u.c.k",
             "f_u_c_k",
             "fag",
             "fagbag",
             "fagfucker",
             "fagg",
             "fagged",
             "fagging",
             "faggit",
             "faggitt",
             "faggot",
             "faggotcock",
             "faggots",
             "faggs",
             "fagot",
             "fagots",
             "fags",
             "fagtard",
             "fcuk",
             "fcuker",
             "fcuking",
             "fingerfuck",
             "fingerfucked",
             "fingerfucker",
             "fingerfuckers",
             "fingerfucking",
             "fingerfucks",
             "fingering",
             "fist fuck",
             "fistfuck",
             "fistfucked",
             "fistfucker",
             "fistfuckers",
             "fistfuckings",
             "fistfucks",
             "fuck",
             "f-u-c-k",
             "fuck buttons",
             "fuck hole",
             "fuck off",
             "fuck puppet",
             "fuck trophy",
             "fuck yo mama",
             "fuck you",
             "fucka",
             "fuckass",
             "fuck-ass",
             "fuckbag",
             "fuck bag",
             "fuck-bitch",
             "fuckboy",
             "fuckbrain",
             "fuckbutt",
             "fuckbutter",
             "fucked",
             "fuckedup",
             "fucked up",
             "fucker",
             "fuckers",
             "fuckersucker",
             "fuckface",
             "fuckhead",
             "fuckheads",
             "fuckhole",
             "fuckin",
             "fucking",
             "fuckings",
             "fuckme",
             "fuck me",
             "fuckmeat",
             "fucknugget",
             "fucknut",
             "fucknutt",
             "fuckoff",
             "fucks",
             "fuckstick",
             "fucktard",
             "fuck-tard",
             "fucktards",
             "fucktart",
             "fucktoy",
             "fucktwat",
             "fuckup",
             "fuckwad",
             "fuckwhit",
             "fuckwit",
             "fuckwitt",
             "fuk",
             "fuker",
             "fukker",
             "fukkers",
             "fukkin",
             "fuks",
             "fukwhit",
             "fukwit",
             "gay sex",
             "gayass",
             "gaybob",
             "gaydo",
             "gayfuck",
             "gayfuckist",
             "gaylord",
             "gays",
             "gaysex",
             "gaytard",
             "gaywad",             
             "genitals",
             "god damn",
             "godamn",
             "godamnit",
             "goddam",
             "god-dam",
             "goddammit",
             "goddamn",
             "goddamned",
             "god-damned",
             "goddamnit",
             "godsdamn",
             "gook",
             "gooks",
             "goregasm",
             "gringo",
             "hitler",
             "holy shit",
             "homodumbshit",
             "homoerotic",
             "jackass",
             "jackasses",
             "jap",
             "japs",
             "jerkass",
             "l3i+ch",
             "l3itch",
             "lameass",
             "lardass",
             "mothafuck",
             "mothafucka",
             "mothafuckas",
             "mothafuckaz",
             "mothafucked",
             "mothafucker",
             "mothafuckers",
             "mothafuckin",
             "mothafucking",
             "mothafuckings",
             "mothafucks",
             "mother fucker",
             "motherfuck",
             "motherfucka",
             "motherfucked",
             "motherfucker",
             "motherfuckers",
             "motherfuckin",
             "motherfucking",
             "motherfuckings",
             "motherfuckka",
             "motherfucks",
             "muthafecker",
             "muthafuckker",
             "mutherfucker",
             "n1gga",
             "n1gger",
             "nazi",
             "nazism",
             "negro",
             "neonazi",
             "nig nog",
             "nigaboo",
             "nigg3r",
             "nigg4h",
             "nigga",
             "niggah",
             "niggas",
             "niggaz",
             "nigger",
             "niggers",
             "niggle",
             "niglet",
             "nig-nog",
             "n1gg4",
             "n1gg3r",
             "p.u.s.s.y.",
             "p.u.s.s.y",
             "paedophile",
             "pedobear",
             "pedophile",
             "pedophilia",
             "pedophiliac",
             "penis",
             "penisbanger",
             "penisfucker",
             "penispuffer",
             "perversion",
             "piece of shit",
             "pigfucker",
             "piss",
             "piss off",
             "piss pig",
             "pissed",
             "pissed off",
             "pisser",
             "pissers",
             "pisses",
             "pissflaps",
             "piss flaps",
             "pissin",
             "pissing",
             "pissoff",
             "piss-off",
             "pisspig",
             "prick",
             "pricks",
             "prickteaser",
             "pussies",
             "pussy",
             "pussys",
             "queef",
             "queer",
             "queerbait",
             "queerhole",
             "queers",
             "reetard",
             "retard",
             "retarded",
             "s.h.i.t.",
             "s_h_i_t",
             "sand nigger",
             "sandnigger",
             "sh!+",
             "sh!t",
             "sh1t",
             "s-h-1-t",
             "shit",
             "shit ass",
             "shit fucker",
             "shitass",
             "shitbag",
             "shitbagger",
             "shitblimp",
             "shitbrains",
             "shitbreath",
             "shitcanned",
             "shitcunt",
             "shitdick",
             "shitfaced",
             "shitfuck",
             "shitfull",
             "shithead",
             "shitheads",
             "shithole",
             "shithouse",
             "skullfuck",
             "slut",
             "slut bucket",
             "slutbag",
             "slutdumper",
             "slutkiss",
             "sluts",
             "smartass",
             "smartasses",
             "son of a bitch",
             "son of a motherless goat",
             "son of a whore",
             "son-of-a-bitch",
             "spic",
             "spooge",
             "spook",
             "spunk",
             "suckass",
             "testical",
             "testicle",
             "titt",
             "tittie5",
             "tittiefucker",
             "titties",
             "titty",
             "tittyfuck",
             "tittyfucker",
             "tittywank",
             "titwank",
             "tranny",
             "twathead",
             "twatlips",
             "twats",
             "twatty",
             "twatting",
             "twatwaffle",
             "vagina",
             "wanker",
             "wankjob",
             "wh0re",
             "wh0reface",
             "white power",
             "whoralicious",
             "whore",
             "whorealicious",
             "whorebag",
             "whored",
             "whoreface",
             "whorehopper",
             "whorehouse",
             "whores",
             "whoring",
        };
    }
}
